// <auto-generated />
using System;
using DoAnMonLapTrinhWeb_Nhom1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnMonLapTrinhWeb_Nhom1.Migrations
{
    [DbContext(typeof(QuanLyThueXeMayTuLaiContext))]
    partial class QuanLyThueXeMayTuLaiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.ChucVu", b =>
                {
                    b.Property<int>("IdchucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDChucVu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdchucVu"));

                    b.Property<string>("TenChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdchucVu")
                        .HasName("PK__ChucVu__70FCCF65DD36D787");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.DanhGium", b =>
                {
                    b.Property<string>("BienSoXe")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("BienSoXe", "Email")
                        .HasName("PK__DanhGia__ED1D49C0256A5A2A");

                    b.HasIndex("Email");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.DiaDiem", b =>
                {
                    b.Property<int>("MaDiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiaDiem"));

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDiaDiem")
                        .HasName("PK__DiaDiem__F015962A8780C2E6");

                    b.ToTable("DiaDiem", (string)null);
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.HangXe", b =>
                {
                    b.Property<int>("MaHangXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHangXe"));

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHangXe")
                        .HasName("PK__HangXe__8C6DD0A7F001ABFF");

                    b.ToTable("HangXe", (string)null);
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MaPhuongThuc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TongDonGia")
                        .HasColumnType("money");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HoaDon__835ED13B8B789FF1");

                    b.HasIndex("MaPhuongThuc");

                    b.HasIndex("Email", "BienSoXe");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaiKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaiKhuyenMai"));

                    b.Property<DateTime>("NgayKhuyenMai")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiDungKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PhanTramKhhuyenMai")
                        .HasColumnType("float");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaiKhuyenMai")
                        .HasName("PK__KhuyenMa__BD611B46F103F3FB");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.LoaiXe", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiXe__730A575939795964");

                    b.ToTable("LoaiXe", (string)null);
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.MailTuDong", b =>
                {
                    b.Property<int>("MaMail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMail"));

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaMail")
                        .HasName("PK__MailTuDo__0DB26639A62061F8");

                    b.ToTable("MailTuDong", (string)null);
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("MaPhuongThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuongThuc"));

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhuongThuc")
                        .HasName("PK__PhuongTh__35F7404EFCC16D3F");

                    b.ToTable("PhuongThucThanhToan", (string)null);
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.Quyen", b =>
                {
                    b.Property<int>("Idquyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDQuyen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idquyen"));

                    b.Property<string>("TenQuyen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Idquyen")
                        .HasName("PK__Quyen__B3A2827E136F0562");

                    b.ToTable("Quyen", (string)null);
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.TaiKhoan", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Avarta")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gplx")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("GPLX");

                    b.Property<int>("IdchucVu")
                        .HasColumnType("int")
                        .HasColumnName("IDChucVu");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<string>("Sdt")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Email")
                        .HasName("PK__TaiKhoan__A9D1053552AD3104");

                    b.HasIndex("IdchucVu");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.Xe", b =>
                {
                    b.Property<string>("BienSoXe")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("money");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("HinhAnh1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDiaDiem")
                        .HasColumnType("int");

                    b.Property<int>("MaHangXe")
                        .HasColumnType("int");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MaLucPhanKhoi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaLuc_PhanKhoi");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NamSanXuat")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("NhienLieu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenXe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("BienSoXe")
                        .HasName("PK__Xe__A7805993CF3E80A0");

                    b.HasIndex("Email");

                    b.HasIndex("MaDiaDiem");

                    b.HasIndex("MaHangXe");

                    b.HasIndex("MaLoai");

                    b.ToTable("Xe", (string)null);
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.YeuCauDatXe", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BienSoXe")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTra")
                        .HasColumnType("datetime");

                    b.Property<int>("SoNgayThue")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThaiChapNhan")
                        .HasColumnType("bit");

                    b.HasKey("Email", "BienSoXe")
                        .HasName("PK__YeuCauDa__83A900AC0247BA4F");

                    b.HasIndex("BienSoXe");

                    b.ToTable("YeuCauDatXe", (string)null);
                });

            modelBuilder.Entity("PhanQuyen", b =>
                {
                    b.Property<int>("IdchucVu")
                        .HasColumnType("int")
                        .HasColumnName("IDChucVu");

                    b.Property<int>("Idquyen")
                        .HasColumnType("int")
                        .HasColumnName("IDQuyen");

                    b.HasKey("IdchucVu", "Idquyen")
                        .HasName("PK__PhanQuye__8BC6E742D5E035C7");

                    b.HasIndex("Idquyen");

                    b.ToTable("PhanQuyen", (string)null);
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.DanhGium", b =>
                {
                    b.HasOne("DoAnMonLapTrinhWeb_Nhom1.Models.Xe", "BienSoXeNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("BienSoXe")
                        .IsRequired()
                        .HasConstraintName("FK__DanhGia__BienSoX__70DDC3D8");

                    b.HasOne("DoAnMonLapTrinhWeb_Nhom1.Models.TaiKhoan", "EmailNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("Email")
                        .IsRequired()
                        .HasConstraintName("FK__DanhGia__Email__6E01572D");

                    b.Navigation("BienSoXeNavigation");

                    b.Navigation("EmailNavigation");
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.HoaDon", b =>
                {
                    b.HasOne("DoAnMonLapTrinhWeb_Nhom1.Models.PhuongThucThanhToan", "MaPhuongThucNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaPhuongThuc")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDon__MaPhuong__73BA3083");

                    b.HasOne("DoAnMonLapTrinhWeb_Nhom1.Models.YeuCauDatXe", "YeuCauDatXe")
                        .WithMany("HoaDons")
                        .HasForeignKey("Email", "BienSoXe")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDon__75A278F5");

                    b.Navigation("MaPhuongThucNavigation");

                    b.Navigation("YeuCauDatXe");
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.TaiKhoan", b =>
                {
                    b.HasOne("DoAnMonLapTrinhWeb_Nhom1.Models.ChucVu", "IdchucVuNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("IdchucVu")
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoan__IDChuc__76969D2E");

                    b.Navigation("IdchucVuNavigation");
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.Xe", b =>
                {
                    b.HasOne("DoAnMonLapTrinhWeb_Nhom1.Models.TaiKhoan", "EmailNavigation")
                        .WithMany("Xes")
                        .HasForeignKey("Email")
                        .IsRequired()
                        .HasConstraintName("FK__Xe__Email__6D0D32F4");

                    b.HasOne("DoAnMonLapTrinhWeb_Nhom1.Models.DiaDiem", "MaDiaDiemNavigation")
                        .WithMany("Xes")
                        .HasForeignKey("MaDiaDiem")
                        .IsRequired()
                        .HasConstraintName("FK__Xe__MaDiaDiem__72C60C4A");

                    b.HasOne("DoAnMonLapTrinhWeb_Nhom1.Models.HangXe", "MaHangXeNavigation")
                        .WithMany("Xes")
                        .HasForeignKey("MaHangXe")
                        .IsRequired()
                        .HasConstraintName("FK__Xe__MaHangXe__74AE54BC");

                    b.HasOne("DoAnMonLapTrinhWeb_Nhom1.Models.LoaiXe", "MaLoaiNavigation")
                        .WithMany("Xes")
                        .HasForeignKey("MaLoai")
                        .IsRequired()
                        .HasConstraintName("FK__Xe__MaLoai__71D1E811");

                    b.Navigation("EmailNavigation");

                    b.Navigation("MaDiaDiemNavigation");

                    b.Navigation("MaHangXeNavigation");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.YeuCauDatXe", b =>
                {
                    b.HasOne("DoAnMonLapTrinhWeb_Nhom1.Models.Xe", "BienSoXeNavigation")
                        .WithMany("YeuCauDatXes")
                        .HasForeignKey("BienSoXe")
                        .IsRequired()
                        .HasConstraintName("FK__YeuCauDat__BienS__6FE99F9F");

                    b.HasOne("DoAnMonLapTrinhWeb_Nhom1.Models.TaiKhoan", "EmailNavigation")
                        .WithMany("YeuCauDatXes")
                        .HasForeignKey("Email")
                        .IsRequired()
                        .HasConstraintName("FK__YeuCauDat__Email__6C190EBB");

                    b.Navigation("BienSoXeNavigation");

                    b.Navigation("EmailNavigation");
                });

            modelBuilder.Entity("PhanQuyen", b =>
                {
                    b.HasOne("DoAnMonLapTrinhWeb_Nhom1.Models.ChucVu", null)
                        .WithMany()
                        .HasForeignKey("IdchucVu")
                        .IsRequired()
                        .HasConstraintName("FK__PhanQuyen__IDChu__778AC167");

                    b.HasOne("DoAnMonLapTrinhWeb_Nhom1.Models.Quyen", null)
                        .WithMany()
                        .HasForeignKey("Idquyen")
                        .IsRequired()
                        .HasConstraintName("FK__PhanQuyen__IDQuy__787EE5A0");
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.ChucVu", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.DiaDiem", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.HangXe", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.LoaiXe", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.PhuongThucThanhToan", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.TaiKhoan", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("Xes");

                    b.Navigation("YeuCauDatXes");
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.Xe", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("YeuCauDatXes");
                });

            modelBuilder.Entity("DoAnMonLapTrinhWeb_Nhom1.Models.YeuCauDatXe", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
